CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
    content TEXT,
    folder INTEGER REFERENCES noteful_folders(id) ON DELETE CASCADE
);